spring.datasource.url=jdbc:postgresql://localhost:5432/hogwarts
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml
logging.level.root=info
path.to.avatars.folder= /avatars
server.port=8080
